
logs_path: "./logs/"
encoded_path: "./encoded/"
checkpoints_path: './checkpoints/'
periodic_checkpoints_path: './periodic_checkpoints/'
saved_models: './saved_models'

cuda: True
load: False

channel_coding: True
channel_strength: '0.2'
channel_encoder: './checkpoints/channel_encoder_s22'
channel_decoder: './checkpoints/channel_decoder_s22'

verbose: False
exp_name: base
verbose_exp_name: base
mask_residual: True
# test_adaptation: True
# none, network, rw_distortion, all_distortion
distortion_method: network
dataset_scale: 1
output_save_interval: 100
checkpoint_interval: 20000
im_height: 400 
im_width: 400
max_epochs: 10
small_secret_size: 14
secret_size: 100
batch_size: 4
workers: 0
lr: 0.00001
# lr: 0.0001

eval_tuning: True
randomize_weights: False
random_min: 0.01
random_max: 10.00

# loss weights
eval_loss_weight: 1
lpips_loss_weight: 1
secret_loss_weight: 1
adv_secret_loss_weight: 1
residual_loss_weight : 1
# a1
adv_similarity_weight : 1
# a2
adv_strength_weight: 1
